package main

import (
	"fmt"
	"regexp"
	"strings"
)

const (
	// sitePath is where the site publishes this directory.
	sitePath = "/docs/reference/definitions/"
	// modulePath is the CUE module the definitions belong to.
	modulePath = "opmodel.dev/core@v2"

	beginMarker = "<!-- generated by task docs:reference from the CUE definitions in src/; DO NOT EDIT -->"
	endMarker   = "<!-- end generated -->"
)

// frontMatter writes the four keys the page dialect allows.
func frontMatter(title, description, typ string, weight int) string {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %q\n", title)
	fmt.Fprintf(&b, "description: %q\n", description)
	if typ != "" {
		fmt.Fprintf(&b, "type: %s\n", typ)
	}
	if weight > 0 {
		fmt.Fprintf(&b, "weight: %d\n", weight)
	}
	b.WriteString("---\n")
	return b.String()
}

// renderIndex writes the generated block of the section page.
func renderIndex(c *catalog) string {
	var b strings.Builder
	b.WriteString("Every definition below belongs to `" + modulePath + "`, the CUE module every OPM artifact is typed against. " +
		"An entry's summary, notes and field comments come from the definition's doc comment; " +
		"its spec, the definitions it uses and the rules CUE enforces are read off the CUE source.\n\n")
	b.WriteString("## Pages\n\n")
	for _, p := range pages {
		fmt.Fprintf(&b, "- [%s](%s%s/): %s\n", p.title, sitePath, p.file, p.description)
	}
	b.WriteString("\n## All definitions\n\n")
	b.WriteString("| Definition | Page | Summary |\n| --- | --- | --- |\n")
	for _, p := range pages {
		for _, n := range p.defs {
			d := c.defs[n]
			doc := parseDoc(n, d.doc)
			sum := strings.ReplaceAll(markdown(doc.summary, n, c.link), "|", `\|`)
			fmt.Fprintf(&b, "| [`%s`](%s) | %s | %s |\n", n, c.link(n), p.title, sum)
		}
	}
	return b.String()
}

// renderPage writes the generated block of one group page.
func renderPage(c *catalog, src string, p *page) (string, error) {
	var b strings.Builder
	links := make([]string, len(p.defs))
	for i, n := range p.defs {
		links[i] = "[`" + n + "`](" + c.link(n) + ")"
	}
	fmt.Fprintf(&b, "Definitions on this page: %s. Every definition is listed on the [definitions page](%s).\n", strings.Join(links, ", "), sitePath)
	for _, n := range p.defs {
		entry, err := renderEntry(c, src, c.defs[n])
		if err != nil {
			return "", err
		}
		b.WriteString("\n")
		b.WriteString(entry)
	}
	return b.String(), nil
}

// renderEntry writes one definition in the fixed order: summary, at a
// glance, spec, example, notes, enforcement. "Served by" has nothing to
// derive from in core and is never written.
func renderEntry(c *catalog, src string, d *def) (string, error) {
	md := func(s string) string { return markdown(s, d.name, c.link) }
	linkList := func(names []string) string {
		out := make([]string, len(names))
		for i, n := range names {
			out[i] = "[`" + n + "`](" + c.link(n) + ")"
		}
		return strings.Join(out, ", ")
	}
	doc := parseDoc(d.name, d.doc)
	g := atAGlance(d)
	spec, err := specSource(src, d)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "## %s\n\n%s\n\n", d.name, md(doc.summary))

	b.WriteString("**At a glance**\n\n")
	fmt.Fprintf(&b, "- Source: `src/%s` in `%s`\n", d.file, modulePath)
	shape := g.shape
	if g.kind != "" {
		shape += ", `kind: " + g.kind + "`"
	}
	fmt.Fprintf(&b, "- Shape: %s\n", shape)
	var embeds []string
	for _, e := range g.embeds {
		if c.pageOf[e] != nil {
			embeds = append(embeds, e)
		}
	}
	if len(embeds) > 0 {
		fmt.Fprintf(&b, "- Embeds: %s\n", linkList(embeds))
	}
	if u := c.uses(d.name); len(u) > 0 {
		fmt.Fprintf(&b, "- Uses: %s\n", linkList(u))
	}
	if u := c.usedBy[d.name]; len(u) > 0 {
		fmt.Fprintf(&b, "- Used by: %s\n", linkList(u))
	}

	fmt.Fprintf(&b, "\n**Spec**\n\n```cue\n%s\n```\n", spec)

	if len(doc.examples) > 0 {
		b.WriteString("\n**Example**\n\n```cue\n")
		for _, ex := range doc.examples {
			for _, l := range exampleLines(ex) {
				b.WriteString(l + "\n")
			}
		}
		b.WriteString("```\n")
	}

	if len(doc.notes) > 0 {
		b.WriteString("\n**Notes**\n\n")
		b.WriteString(renderBlocks(doc.notes, md))
	}

	if rules := enforcement(d); len(rules) > 0 {
		fmt.Fprintf(&b, "\n**Enforcement**\n\nCUE enforces each of these rules on a value unified with `%s`:\n\n", d.name)
		for _, r := range rules {
			fmt.Fprintf(&b, "- %s\n", md(r.text))
			if r.code != "" {
				fmt.Fprintf(&b, "\n  ```text\n  %s\n  ```\n\n", r.code)
			}
		}
	}
	return b.String(), nil
}

var reQuoted = regexp.MustCompile(`"(?:[^"\\]|\\.)*"`)

// exampleLines turns "Example:" values into one quoted value per line, and a
// "Usage:" line "expr => result" into the expression with its result as a
// comment.
func exampleLines(ex example) []string {
	if ex.usage {
		if i := strings.Index(ex.text, "=>"); i > 0 {
			return []string{strings.TrimSpace(ex.text[:i]) + " // " + strings.TrimSpace(ex.text[i+2:])}
		}
		return []string{ex.text}
	}
	if vals := reQuoted.FindAllString(ex.text, -1); len(vals) > 0 {
		return vals
	}
	return []string{ex.text}
}

// renderBlocks writes note paragraphs as Markdown: prose paragraphs, list
// items, and indented lines as a text block.
func renderBlocks(blocks []*block, md func(string) string) string {
	var b strings.Builder
	inText := false
	prevList := false
	for _, bl := range blocks {
		if bl == nil {
			if inText {
				b.WriteString("```\n")
				inText = false
			}
			continue
		}
		switch {
		case bl.verbatim && strings.HasPrefix(bl.text, "- "):
			if inText {
				b.WriteString("```\n")
				inText = false
			}
			if !prevList && b.Len() > 0 {
				b.WriteString("\n")
			}
			b.WriteString("- " + md(strings.TrimPrefix(bl.text, "- ")) + "\n")
			prevList = true
			continue
		case bl.verbatim:
			if !inText {
				if b.Len() > 0 {
					b.WriteString("\n")
				}
				b.WriteString("```text\n")
				inText = true
			}
			b.WriteString(strings.TrimSpace(bl.text) + "\n")
		default:
			if inText {
				b.WriteString("```\n")
				inText = false
			}
			if b.Len() > 0 {
				b.WriteString("\n")
			}
			b.WriteString(md(bl.text) + "\n")
		}
		prevList = false
	}
	if inText {
		b.WriteString("```\n")
	}
	return b.String()
}
